// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNMhXuMIazTmnmXhIanXq6dJcGtjDgiE',
    appId: '1:951884656040:web:8c88b0af239ee46d75c19d',
    messagingSenderId: '951884656040',
    projectId: 'work-permit-4c80a',
    authDomain: 'work-permit-4c80a.firebaseapp.com',
    storageBucket: 'work-permit-4c80a.appspot.com',
    measurementId: 'G-2J5PBMPWJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ33fpgwAQKKTJfu5Ab_p-0Iyykt8IV54',
    appId: '1:951884656040:android:0ea606f2b68c94be75c19d',
    messagingSenderId: '951884656040',
    projectId: 'work-permit-4c80a',
    storageBucket: 'work-permit-4c80a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmNqyM9UsIRV9oovZ4asVo4w0UnBSvjys',
    appId: '1:951884656040:ios:9160363ddd23578675c19d',
    messagingSenderId: '951884656040',
    projectId: 'work-permit-4c80a',
    storageBucket: 'work-permit-4c80a.appspot.com',
    iosBundleId: 'com.zingworks.workpermit',
  );

}