// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNMhXuMIazTmnmXhIanXq6dJcGtjDgiE',
    appId: '1:951884656040:web:8c88b0af239ee46d75c19d',
    messagingSenderId: '951884656040',
    projectId: 'work-permit-4c80a',
    authDomain: 'work-permit-4c80a.firebaseapp.com',
    storageBucket: 'work-permit-4c80a.appspot.com',
    measurementId: 'G-2J5PBMPWJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU1ZSqsXUL1JWVWjsr1q-hPTwgPjNpUJs',
    appId: '1:114371237530:android:a92a0e193127f85bc3b123',
    messagingSenderId: '951884656040',
    projectId: 'work-permit-dev',
    storageBucket: 'work-permit-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKhHJEk6Vh_AV2Do_2SW-djdpGjWGs9dw',
    appId: '1:114371237530:ios:094e74670a668ad6c3b123',
    messagingSenderId: '951884656040',
    projectId: 'work-permit-dev',
    storageBucket: 'work-permit-dev.appspot.com',
    iosBundleId: 'com.zingworks.workpermitdev',
  );
}
